theme: minima
#remote_theme: jekyll/minima

header_pages:
  - elements-code-tutorial/part-one.md

# Build settings
markdown: kramdown

# Site settings
#    Used to personalize the site. If you look in the HTML files,
#    you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#    You can create any custom variable you like, and they will be accessible
#    in the templates via {{ site.myvariable }} for example.
url: "https://wintercooled.github.io" 
baseurl: "" # the subpath of your site if neded, e.g. /sitecontent

email: wintercooled@gmail.com
twitter_username: wintercooled
github_username:  wintercooled

title: wintercooled.github.io
description: >- # this means to ignore newlines
  Just an example Jekll site. This will appear in document head meta (for
  Google search results) and feed.xml site description.


