theme: minima
#remote_theme: jekyll/minima

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Site settings
#    Used to personalize the site. If you look in the HTML files,
#    you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
#    You can create any custom variable you like, and they will be accessible
#    in the templates via {{ site.myvariable }} for example.
url: "https://wintercooled.github.io" 
baseurl: "" # the subpath of your site if neded, e.g. /sitecontent

title: wintercooled.github.io
description: >- # this means to ignore newlines
  A dumping ground for random texts on Bitcoin.


github_link: https://github.com/wintercooled/wintercooled.github.io
